---
- name: update apt cache
  apt: update_cache=yes
  sudo: true

- name: install default apps
  apt: pkg={{ item }} state=latest install_recommends=no
  with_items:
    - git
    - vim
    - htop
    - tmux

- name: dotrepo
  git: repo=git://github.com/3nodedev/dotfiles.git dest=dotfiles
  become_user: vagrant

# - name: dotrepo
#   become_user: vagrant
#   command: sh /home/{{ rbenv.rbenv_user }}/dotfiles/makesymlinks.sh
